### PR TITLE
Create git tag for 1.2.5 - Breaks other PEAR packages

### PR DESCRIPTION
**Pull request by smcjones**
Can this be converted to a git SVN tag? 

    tag 1.2.5
    git push origin 1.2.5

git-svn-id: http://svn.php.net/repository/pear/packages/HTML_Common/tags/RELEASE_1_2_5@278216 c90b9560-bf6c-de11-be94-00142212c4b1

### CODE REVIEW

**Comment by smcjones** [comment]
Please note that I would have left an issue or a bug in pear.php.net, but pear.php.net bugs are not currently working, and issues are not open for these repos.

**Comment by cweiske** [comment]
I've correctly tagged the release commits now.

**Comment by cweiske** [comment]
What do you mean by "but pear.php.net bugs are not currently working"? They should be, and they did yesterday.

**Comment by ashnazg** [comment]
I think this is what they mean:
image

**Comment by cweiske** [comment]
@ashnazg that was you with http_upload 1.0.0b4. After downgrading to b3 it works again :) https://pear.php.net/bugs/bug.php?id=21185

**Pull request closed without merging**
